server:
  port: 9002

spring:
  application:
    name: demo-02 #指定服务名

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true

feign:
  hystrix:
    enabled: true