server:
  port: 9002

spring:
  application:
    name: demo-02 #指定服务名

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.40.238:8848
    sentinel:
      transport:
        port: 8720
        dashboard: localhost:9000
feign:
  sentinel:
    enabled: true