server:
  port: 9003

spring:
  application:
    name: demo-03 #指定服务名

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6868/eureka
  instance:
    prefer-ip-address: true